//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAttendanceWPF.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSchoolAttendanceEntities : DbContext
    {
        public dbSchoolAttendanceEntities()
            : base("name=dbSchoolAttendanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblClassSubject> tblClassSubject { get; set; }
        public virtual DbSet<tblSchoolClass> tblSchoolClass { get; set; }
        public virtual DbSet<tblSchoolLevel> tblSchoolLevel { get; set; }
        public virtual DbSet<tblSchoolYear> tblSchoolYear { get; set; }
        public virtual DbSet<tblSchoolYearTerm> tblSchoolYearTerm { get; set; }
        public virtual DbSet<tblStudent> tblStudent { get; set; }
        public virtual DbSet<tblSubjectAttendance> tblSubjectAttendance { get; set; }
        public virtual DbSet<tblSubjectRegistration> tblSubjectRegistration { get; set; }
    }
}
