//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAttendanceWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClassSubject()
        {
            this.tblSubjectAttendance = new HashSet<tblSubjectAttendance>();
            this.tblSubjectRegistration = new HashSet<tblSubjectRegistration>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SchoolClassID { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        public virtual tblSchoolClass tblSchoolClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubjectAttendance> tblSubjectAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSubjectRegistration> tblSubjectRegistration { get; set; }
    }
}
