//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAttendanceWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchoolYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSchoolYear()
        {
            this.tblSchoolYearTerm = new HashSet<tblSchoolYearTerm>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> YearStartDate { get; set; }
        public Nullable<System.DateTime> YearEndDate { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchoolYearTerm> tblSchoolYearTerm { get; set; }
    }
}
