//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolAttendanceWPF.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubjectAttendance
    {
        public int ID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string Notes { get; set; }
    
        public virtual tblClassSubject tblClassSubject { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
